---
- name: Clone leaderboard-gitops
  ansible.builtin.git:
    repo: https://{{ gitea_customize_gitea_admin_user }}:{{ gitea_customize_gitea_admin_password }}@{{
          gitea_customize_gitea_endpoint }}/{{ gitea_customize_gitea_admin_user }}/leaderboard-gitops.git
    dest: /tmp/leaderboard-gitops
    single_branch: yes
    version: main

- name: Fetch values.yaml file from remote host
  run_once: true
  ansible.builtin.fetch:
    src: /tmp/leaderboard-gitops/values.yaml
    dest: /tmp/dest/values.yaml
    flat: true
    fail_on_missing: true

- name: Apply template /tmp/dest/values.yaml
  ansible.builtin.template:
    src: /tmp/dest/values.yaml
    dest: /tmp/leaderboard-gitops/values.yaml

- name: Add new files to the repository
  ansible.builtin.command:
    chdir: >-
      /tmp/leaderboard-gitops
    cmd: "git add ."
  ignore_errors: true

- name: Commit changes to the repository
  ansible.builtin.command:
    chdir: >-
      /tmp/leaderboard-gitops
    cmd: >-
      git commit -a -m 'Updates for starting scenario.'
  ignore_errors: true

- name: Push all changes back to the project repository
  ansible.builtin.command:
    chdir: >-
      /tmp/leaderboard-gitops
    cmd: >-
      git push